### ISSUE TITLE
 Missing train_mode Config Params?

### ISSUE THREAD

**Issue by Minotaur-CN** [tensorlayer/openpose#10]
Hi .

Are there some Param missing on file config.py? I can not train missing train_mode params.

Thanks for your reply!

Traceback (most recent call last):
  File "train.py", line 197, in <module>
    if config.TRAIN.train_mode == 'placeholder':
AttributeError: 'EasyDict' object has no attribute 'train_mode'

**Comment by zsdonghao** [comment]
em.. Sorry for that. Just update the config.py by adding:

```
config.TRAIN.train_mode == 'placeholder'
```

This project still WIP, the training with placeholder is finished, but the inferencing still need time.

**Comment by Minotaur-CN** [comment]
Thanks donghao,
The training processing could be run. Thanks for your update.
1. However the training GPU-Util are not high , most of the time are idle.
2. This code only used for single GPU? my multi-gpu seems not working properly!.

Thanks!

**Comment by zsdonghao** [comment]
I update the train file last night https://github.com/tensorlayer/openpose/pull/11  wait for merging ..

The current version only support for single GPU.

**Comment by zsdonghao** [comment]
@Minotaur-CN pls use the latest update to train the model.
