### ISSUE TITLE
build cpp error

### ISSUE THREAD

**Issue by qq160816** [tensorlayer/openpose#22]
Scanning dependencies of target see-pose
make[4]: Leaving directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/cmake-build/Linux'
make[4]: Entering directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/cmake-build/Linux'
[ 33%] Building CXX object CMakeFiles/see-pose.dir/src/input.cc.o
[ 66%] Building CXX object CMakeFiles/see-pose.dir/src/main.cc.o
In file included from /home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/main.cc:9:0:
/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/timer.h:7:7: error: using typedef-name ‘timer_t’ after ‘class’
 class timer_t
       ^
In file included from /usr/include/time.h:47:0,
                 from /usr/include/pthread.h:24,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/memory:73,
                 from /home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/main.cc:1:
/usr/include/x86_64-linux-gnu/bits/types/timer_t.h:7:19: note: ‘timer_t’ has a previous declaration here
 typedef __timer_t timer_t;
                   ^
/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/main.cc: In function ‘void pose_example(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/main.cc:36:41: error: invalid conversion from ‘const void*’ to ‘timer_t {aka void*}’ [-fpermissive]
         timer_t _("create_pose_detector");
                                         ^
/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/src/main.cc:44:46: error: invalid conversion from ‘const void*’ to ‘timer_t {aka void*}’ [-fpermissive]
             timer_t _("get_detection_tensors");
                                              ^
CMakeFiles/see-pose.dir/build.make:86: recipe for target 'CMakeFiles/see-pose.dir/src/main.cc.o' failed
make[4]: *** [CMakeFiles/see-pose.dir/src/main.cc.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/cmake-build/Linux'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/see-pose.dir/all' failed
make[3]: *** [CMakeFiles/see-pose.dir/all] Error 2
make[3]: Leaving directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/cmake-build/Linux'
Makefile:83: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app/cmake-build/Linux'
Makefile:21: recipe for target 'see_pose' failed
make[1]: *** [see_pose] Error 2
make[1]: Leaving directory '/home/wangweilin/wwl/openpose/tensorlayer/openpose/cpp/examples/app'
Makefile:30: recipe for target 'opencv_example' failed
make: *** [opencv_example] Error 2

**Comment by lgarithm** [comment]
This is due to name conflict with standard C/C++ header.
I've changed the name https://github.com/tensorlayer/openpose/commit/4e62cd4f12c7f97fd7746b242c245329c465709d.
